- id: doi:10.1021/acscatal.3c05333
  image: "images/paper-24-1.webp"


- id: doi:10.1021/acscatal.3c04995
  image: "images/paper-24-2.gif"

- id: doi:10.1038/s41467-023-44452-z
  image: "images/paper-24-3.webp"